### ISSUE TITLE
PStack plusAll, unexpected result

### ISSUE THREAD

**Issue by imrafaelmerino** [hrldcpr/pcollections#77]
```
//[1,2]
final ConsPStack<Integer> xs = ConsPStack.<Integer>empty().plus(2).plus(1);

System.out.println(xs); // [1,2]

//[3,4]
final ConsPStack<Integer> ys = ConsPStack.<Integer>empty().plus(4).plus(3);

System.out.println(ys); // [3,4]

final ConsPStack<Integer> zs = ys.plusAll(xs);

//expected : [1,2,3,4]
System.out.println(zs); // [2,1,3,4]
```

**Comment by hrldcpr** [comment]
Hey thanks for pointing this out, it's definitely confusing…

It's because `c = c.plusAll(d)` is equivalent to:
```java
for (E e : d) c = c.plus(e);
```
…so popping things off one stack and pushing them onto another ends up reversing them.

I'm not sure what the best solution is …changing the behavior at this point might break some people's code in hard-to-detect ways (though of course we would do a major version bump). Potentially could deprecate `ConsPStack.plusAll` in favor of some less confusing / better-named alternative methods.
